### ISSUE TITLE
希望在启用模块后息屏时可以把屏幕锁定时间设为永不锁定

### ISSUE THREAD

**Issue by lfsjww** [Xposed-Modules-Repo/me.neversleep.plusplus#10]

**Comment by dangerboy1986** [comment]
对，虽然当时没有锁屏，但是过了一会儿，到了系统设定。的。锁屏时间还是会锁屏。

**Comment by jitcor** [comment]
可以试下这个版本：[1.7.2_20240528_084046_release.apk.zip](https://github.com/jitcor/FakeScreen/files/15462884/1.7.2_20240528_084046_release.apk.zip)
