### ISSUE TITLE
貌似无法在澎湃OS下使用了

### ISSUE THREAD

**Issue by zerofo** [Xposed-Modules-Repo/me.neversleep.plusplus#13]
https://github.com/Genymobile/scrcpy/issues/3927
scrcpy 的息屏功能也是  不知道是不是安卓14的关系 。。 求支持

**Comment by Umr115** [comment]
小米13 HyperOS Android14 也失效了。

**Comment by langkiss** [comment]
是的好像是安卓14的原因，不知道作者会不会想起来更新啦

**Comment by zerofo** [comment]
scrcpy 2.3 已经可以正常使用关屏了。。
 希望作者 @Humenger 跟进一下
 https://github.com/Genymobile/scrcpy/commit/5d4b8a7e6d18ee0e19a764945dc67efbd46f3e97

**Comment by jitcor** [comment]
https://github.com/jitcor/FakeScreen/releases/tag/v1.6 测试下看看

**Comment by NestRoomPast** [comment]
> https://github.com/jitcor/FakeScreen/releases/tag/v1.6 测试下看看

基于安卓14点澎湃OS，正常工作

**Comment by zerofo** [comment]
小米10pro 安卓14 澎湃OS, 测试正常了
