### ISSUE TITLE
module not working ?

### ISSUE THREAD

**Issue by ELKecham** [Xposed-Modules-Repo/me.neversleep.plusplus#2]
android 12.1 rom Crdroid 8.4 begonia/remi note 8 pro

module installs and start but when i press power button again the phone screen dont respond (dont power on again)  need force reboot pressing power button to screen "work" again

**Comment by ELKecham** [comment]
i use screen back light OFF app but this app overheat the phone

**Comment by Humenger** [comment]
Upload the module log here.

**Comment by Humenger** [comment]
If possible, try to submit the logs of `adb logcat -s neversleep` obtained by the adb command.

**Comment by ELKecham** [comment]
![IMG-20220504-WA0000](https://user-images.githubusercontent.com/102772308/166629984-152b6733-4f8e-4f16-8d61-b219dacd789b.jpeg)
`
Like this ? I used screen mirror to take the photo the screen stop working too when screen is off and used termux to see logcat

**Comment by Humenger** [comment]
Confirm through the log that the program is running normally. But I don't quite understand your question. If possible, could you demonstrate it with a video?

**Comment by ELKecham** [comment]
https://user-images.githubusercontent.com/102772308/166816470-608b66f8-874f-45a4-8406-432e193f0abc.mp4

here the video 

When screen is off the touch dont work (idk if possible or this is the way it works)but the screen cant get powered when i press the power button again

**Comment by Humenger** [comment]
[FakeScreen_1.6_beta.apk.zip](https://github.com/Xposed-Modules-Repo/me.neversleep.plusplus/files/8628275/FakeScreen_1.6_beta.apk.zip)

Try this version and get the running log with the following adb command.
```
adb logcat -s neversleep
```

**Comment by ELKecham** [comment]
![Screenshot_20220505-025414_Termux.png](https://user-images.githubusercontent.com/102772308/166869738-2c9dc419-bd55-4413-ace8-06964880d5e7.png)

**Comment by ELKecham** [comment]
i done some testing and if i "turn on" the screen i can get the touch to work again when the system thinks the screen is off the touch dont work but if i press the power button the screen continue black but i can control the touch and if i dont close the program i can turn of the switch and press 2x the power button then the screen power on again

**Comment by Humenger** [comment]
So it is normal to turn off the screen, but not to turn on the screen normally?

**Comment by ELKecham** [comment]
Yes the app turn off the screen but not turn back on .... only if i do this trick i said you using screen share ....

**Comment by Humenger** [comment]
Run the following adb command to get the running log, then press "ctrl+c" to terminate, and upload the `fakescreen.log` file here.

```
adb logcat > fakescreen.log
```

**Comment by ELKecham** [comment]
i just removed my email and auth key i think its good :)
[fakescreen.log](https://github.com/Xposed-Modules-Repo/me.neversleep.plusplus/files/8637393/fakescreen.log)

Dont have much to steal anyway xD
Ive search plusplus and neversleep and found some lines hope it helps find the error

**Comment by Humenger** [comment]
This log also looks normal. At present, I guess it may be related to the MTK chip in your mobile phone. I don't have a mobile phone with this chip here, so I can't test it specifically.

**Comment by ELKecham** [comment]
Ive found a work around using any app that enable remap buttons .... ican remap any button to use this command of your app am start -n me.neversleep.plusplus/.MainActivity --ez power false and then when i press 2x the power - button the program get closed and i can get the app to work normaly :)

**Comment by ELKecham** [comment]
Sooo if u need some log or anything to the app on my phone u can tell/contact me im going to use the app using button remap so i can watch videos in big screen :)
