### ISSUE TITLE
是否考虑增加它的功能

### ISSUE THREAD

**Issue by yijiangchengming** [Xposed-Modules-Repo/me.neversleep.plusplus#3]
是否可以暴露一个shell命令，或者一个快捷方式，使得可以控制应用内的开关。
例如:我希望它在白天不工作，因为不锁屏是不安全的。
但是我希望它在晚上我睡觉时工作。因为MIUI的闹钟有概率失灵。

**Comment by Humenger** [comment]
The latest version is supported, please update.
