### ISSUE TITLE
shell命令开启有点问题

### ISSUE THREAD

**Issue by paipaitou** [Xposed-Modules-Repo/me.neversleep.plusplus#4]
执行am start -n me.neversleep.plusplus/.MainActivity --ez power true后，会跳出来模块主界面，还有就是磁贴的相应按钮不会变亮，也就是选中状态

**Comment by Humenger** [comment]
会跳出来模块主界面是因为模块之前就已经打开了。\
磁贴按钮点击后，部分设备需要等待一定的延迟后，才会开启/关闭，在此期间不要频繁点击按钮。
