### ISSUE TITLE
安卓12MIUI13息屏后点不亮

### ISSUE THREAD

**Issue by yushi118** [Xposed-Modules-Repo/me.neversleep.plusplus#6]
点电源键息屏后再点就点不亮了，可以操作屏幕暂停视频什么的，但就是屏幕还是息屏状态，很喜欢这个模块，求作者大大修复

**Comment by Humenger** [comment]
什么机型

**Comment by yushi118** [comment]
红米K50



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月25日(周三) 下午4:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/me.neversleep.plusplus] 安卓12MIUI13息屏后点不亮 (Issue #6)




 
什么机型

**Comment by Humenger** [comment]
初步猜测为MTK联发科机型问题，该issue也提了一次https://github.com/Xposed-Modules-Repo/me.neversleep.plusplus/issues/2

目前本人没有该类MTK手机，无法做测试。若是想急于解决该问题，你可以临时采用上面issue的做法，做个按键映射

**Comment by Ja-sagen** [comment]
> 什么机型
K50G，高通的U，也是一样，锁屏后点不亮

**Comment by chenxuuu** [comment]
k50u也是如此（骁龙8+）

**Comment by NAHXiao** [comment]
我的手机(redmi note11t pro)也出现了这个问题,不过我发现虽然有时息屏后点不亮,但此时触控还是可以用的、并且仔细看还是可以看到屏幕上的字,此时如果调节亮度、下滑通知栏、打开最近任务界面等均可以点亮屏幕,可以利用这个曲线救国(我就是)

**Comment by zsaaa321456** [comment]
我也有这个问题，我是lgv50  高通骁龙855，同一台手机刷了别的两个包，息屏之后无法点亮，但以前用的一个包是正常使用的，不知道啥原因

**Comment by Yuameshi** [comment]
我的K30Ultra(cezanne).也有这种问题，Android12 MIUI13，息屏后无法点亮，触控能操作，显示黑屏。
```
API 版本
93

Xposed API 调用保护
未启用

Dex 优化器包装
支持

框架版本
1.8.6 (6712)

管理器版本
1.8.6 (6712)

系统版本
12 (API 31)

设备
Xiaomi Redmi M2006J10C 

系统架构
arm64-v8a
```

**Comment by rightester** [comment]
红米Note11TPro Android12 MIUI13 同此问题，soc天玑8100
